### PR TITLE
Dapper.Contrib Nullable ID (#581)

### PR DESCRIPTION
**Pull request by jurakovic**
Added support for Nullable ID property in Dapper.Contrib
Fix for issue #581

### CODE REVIEW

**Comment by NickCraver** [comment]
Can you please provider any tests illustrating the use case this fixes?

**Comment by jurakovic** [comment]
I have added InsertUserNullableId test
For some reason i cannot run tests in VS. No errors are shown so I don't know where is the problem  :/
But I have tested it somehow outside of solution and it passes :)

**Comment by gilb195** [comment]
I've been experiencing this issue as well since I'm using a nullable int for the ID in my models. Thank you @jurakovic for this PR - would love to see this merged and fixed soon.

**Comment by NickCraver** [comment]
I can't speak to Contrib's future plans here and if this is a good fit, but please see #1658 - Dapper.Contrib is not located at https://github.com/DapperLib/Dapper.Contrib (separate from this repository). 

Note: I based the Dapper.Contrib fork on the original codebase which hopefully makes porting pull requests against the main branch there much easier - the intent was to split, not throw away work the community wants to go with.

**Pull request closed without merging**
