### PR TITLE
Add SQLAnywhere support

### PR DESCRIPTION
**Pull request by xiaoningmzhang**
I also had a solution to support SQL Anywhere (see issue #879).

### CODE REVIEW

**Comment by xiaoningmzhang** [comment]
My company depends on Sybase, and I would like to get this work pulled in.  Is there any additional contributor guidelines I need to know about or more work that is needed to be done?

**Comment by mgravell** [comment]
for context, I'm not historically very involved in contrib; reviewing this, it looks like this is a breaking change (changes a public interface) which caller's could have implemented themselves and passed in via the optional parameter on `InsertAsync`. Not sure how we can rationalize that.

Note: there's also a *lot* wrong with this API generally, but that isn't your fault - I just looked at it right now, and want to weep gently :(

FWIW, I think what we *should* have used here is an abstract base class API which might have made this more extensible, but: I think we should add this into the "major breaking changes" bucket

**Comment by NickCraver** [comment]
Indeed we can't pull this in as it is a breaking change. We really need to revisit Dapper.Contrib as a whole - maybe this is a sabbatical project?

**Comment by NickCraver** [comment]
I can't speak to Contrib's future plans here and if this is a good fit, but please see #1658 - Dapper.Contrib is not located at https://github.com/DapperLib/Dapper.Contrib (separate from this repository). 

Note: I based the Dapper.Contrib fork on the original codebase which hopefully makes porting pull requests against the main branch there much easier - the intent was to split, not throw away work the community wants to go with.

**Pull request closed without merging**
