### PR TITLE
Add StreamAsync alternatives to support IAsyncEnumerable

### PR DESCRIPTION
**Pull request by dwfrancis**
Add `StreamAsync` alternatives to `connecton.QueryAsync` and `gridReader.ReadAsync` to support `IAsyncEnumerable` in a non-breaking way.

Unlike `QueryAsync`, stream will default to unbuffered.

### CODE REVIEW

**Comment by dwfrancis** [comment]
Intentionally omitted cancellation tokens to keep the signatures similar. 

Since these are new I can include them.

**Comment by dwfrancis** [comment]
Re-authored commits (forgot to reset git config from a work account)

**Comment by dwfrancis** [comment]
Completes the "new IAsyncEnumerable<T> API" task #1293

**Comment by mgravell** [comment]
Will review when I'm back at in work-mode.

**Comment by fdcastel** [comment]
> Will review when I'm back at in work-mode.

@mgravell... Are you back from your sabbatical? 😅

@dwfrancis Thanks for the excellent work! I'm using the code in some non-production capacity (going into production next month) and so far it is going smoothly. 👍

**Comment by Sonic198** [comment]
I'm also waiting for that :D

**Comment by pcooper** [comment]
I was able to work around lack of support with the current stable version by using `ExecuteReaderAsync` to get a data reader, then get a row parser from that.

```cs
var reader = await connection.ExecuteReaderAsync(sql, param);
var rowParser = reader.GetRowParser<MyType>();
while (await reader.ReadAsync())
{
  var value = rowParser(reader);
  // Do other sync/async stuff with value.
  yield return value;
}
```

This also worked with `dynamic` typed row parser funcs.

**Comment by Conbag93** [comment]
Just wanted to also add my thanks to @dwfrancis for this PR.
I hope that it gets the offical 'nod' of approval because this has allowed me to experiment with some of the new-ish .net features wiith very minimal code changes.

Combining this with System.Text.Json's newly introduced support for asynchronous Json serialization allows my API to return each row to the client as soon as they are retrieved from the database.
Additionally, if the client also knows the "count" ahead-of-time then I can leverage this to track the progress of a long-running query.

**Comment by SoftStoneDevelop** [comment]
It looks like a different implementation of what I did(https://github.com/DapperLib/Dapper/pull/1882) as part of the solution https://github.com/DapperLib/Dapper/issues/1239 (because in the comments to the issue it was https://github.com/DapperLib/Dapper/issues/1239#issuecomment-1035448069).

The fundamental difference is that I rewrote SqlMapper.Async and SqlMapper.GridReader.Async from pseudo-async to IAsyncEnumerable. And of course added "buffered" parameter.
Because my opinion is that there should be either a synchronous method or an asynchronous one. A pseudo-asynchronous wrapper over a synchronous one has no right to exist.

My point is that it might be worth choosing one of these two pull requests or considering them together.

**Comment by ronimizy** [comment]
Any updates on that? 👀

**Comment by SoftStoneDevelop** [comment]
> Any updates on that? 👀

No, Dapper seems to be abandoned.

**Comment by mgravell** [comment]
Dapper is absolutely not abandoned; see #1909 for status; this feature now essentially provided via #1912 - so: I appreciate the input, but I think we should re-address needs when #1912 is in

**Pull request closed without merging**
