### PR TITLE
Add column attribute for properties.

### PR DESCRIPTION
**Pull request by Sjoo90**
This pull request adds a new attribute for properties to name-mapping for Dapper.Contrib.

### CODE REVIEW

**Comment by Sjoo90** [comment]
@mgravell @NickCraver can you take a look at this? This solution I use in my project to help my columnmapping for Dapper.Contrib.

**Comment by NickCraver** [comment]
Hey Patric! First, thanks for the ideas and contribution here.

Unfortunately, this problem is much larger to solve holistically. We're trying to map that out in #722 on what to do in v3 - it's something we need to step back and design into the core of Dapper to make it work properly.

On this PR specifically, the changes add to an interface which is a breaking change for all downstream consumers (they'll get a `MissingMethodException`). That's not something we can merge in without breaking people...and in the next break we're going to add much more integrated support anyhow. Does that make sense? I'm happy to discuss further, but we'd ideally have time ASAP but the reality is it's going to be a while and with breaks it has to be coordinated...so we want to do such breaks as rarely as possible.

**Comment by TrevorDArcyEvans** [comment]
Similar changes are also needed for _Insert_

**Comment by NickCraver** [comment]
I can't speak to Contrib's future plans here and if this is a good fit, but please see #1658 - Dapper.Contrib is not located at https://github.com/DapperLib/Dapper.Contrib (separate from this repository). 

Note: I based the Dapper.Contrib fork on the original codebase which hopefully makes porting pull requests against the main branch there much easier - the intent was to split, not throw away work the community wants to go with.

**Pull request closed without merging**
