### PR TITLE
fix inconsistent Contrib column name formatting in postgres and test

### PR DESCRIPTION
**Pull request by nathan-c**
I realise this is technically a change in behaviour but it actually represents a standardisation in how postgres column names are treated. 

This is intended to add quotes to all column names when using postgres. The current behaviour omits quotes for id column on get and also on insert when getting an id back but uses quotes for all other operations and columns.

My personal preference would be to support snake_case names and not use quotes at all as this is more in line with postgres standard practise. I realise this has been talked about in #722 

Note that this change does not affect the fact the Contrib currently does not quote table names so there is still an inconsistency between table and column name handling.

### CODE REVIEW

**Comment by NickCraver** [comment]
We'll be addressing this in #722 (v2) as mentioned above...but we cannot take such a change in v1. It's absolutely a breaking change for many users...we can't ship this change in a minor version. Honestly, I wouldn't support doing it in a major version. I think we'll maintain the current behavior in v2 but allow users to have full control easily - most people using 1-2 lines of config to use the rules they want (some in-box).

**Comment by nathan-c** [comment]
To confirm. Currently `Get` and `Insert` expect lower case keys but `Delete` and `Update` require a case sensitive key column. I have updated the branch to show all the failing tests if behaviour stays the same.

I didn't expect this behaviour during a MSSQL -> PG migration. 

How can I stay up to date (or even help) with v2 work?

**Comment by nathan-c** [comment]
This behaviour is also noted in a recent issue #1213

**Comment by rclarke2050** [comment]
I found a way around this field name problem for the time being.

in my Repository Constructor i used:

DapperExtensions.DapperExtensions.SqlDialect = new DapperExtensions.Sql.PostgreSqlDialect();

and in the Insert Method:   db.Insert(item); 
and in the Updaet Method: db.Update(item);

i did not use the SqlMapper approach, nor did I use the SqlMapperExtensions.Insert()

Ive tried on .Net Core 2.1 Lambda, and AWS Aurora 10.7.

Dapper v2.0.30
Dapper.Contrib 2.0.30
DapperExtensions.DotnetCore 1.0.1

I hope this helps others for now....in the interim.

**Comment by NickCraver** [comment]
I can't speak to Contrib's future plans here and if this is a good fit, but please see #1658 - Dapper.Contrib is not located at https://github.com/DapperLib/Dapper.Contrib (separate from this repository). 

Note: I based the Dapper.Contrib fork on the original codebase which hopefully makes porting pull requests against the main branch there much easier - the intent was to split, not throw away work the community wants to go with.

**Pull request closed without merging**
