### PR TITLE
auto-detect stored procedures as anything without whitespace

### PR DESCRIPTION
**Pull request by mgravell**
also, we have public fields? (hangs head in shame)

### CODE REVIEW

**Comment by kirylbokach** [comment]
Unfortunately this change breaks all single word commands, like `COMMIT` and `ROLLBACK`

**Comment by mgravell** [comment]
@kirylbokach https://github.com/DapperLib/Dapper/pull/1995 thanks!

**Comment by crayzd92** [comment]
This change also breaks the `REVERT` command

**Comment by mgravell** [comment]
K, will fix

**Comment by SSMKittel** [comment]
Also affects the "analyze" command in postgres. https://www.postgresql.org/docs/current/sql-analyze.html

**Pull request merged**
