### PR TITLE
Added support for net462 and net6.0/net7.0 

### PR DESCRIPTION
**Pull request by verrigo**
Dropped support for net461 and net5.0 as they are out of service
Added support for net462 and net6.0. And for Dapper and Dapper.Strongname also for net7.0
Fixed issue https://github.com/DapperLib/Dapper/issues/1886
Added possibility to debug the Benchmark Project from an IDE
Moved appveyor image up to Visual Studio 2022

### CODE REVIEW

**Comment by mgravell** [comment]
This doesn't "add support" for net6/net7 - they were already perfectly well supported. All this does is *remove* support for anyone using net5 - or at least, pushes them to use the netstandard2.0 build.

Now, I can *sort of* get behind removing the obsolete ones and migrating to current, but there's no point having both net6 and net7 **unless** there is a difference between them, usually via `#if`. But I'll need to review on a PC (on mobile at the moment) to see more.

**Comment by mgravell** [comment]
I actually missed the important bit "Fixed issue #1886" on first review. Honestly, I think that should be a separate PR, rather than bundling everything all together.

**Comment by mgravell** [comment]
The petapoco change: is this simply an update of current code from the petapoco repo? If so, fine - but: we shouldn't be "fixing" petapoco here

**Comment by verrigo** [comment]
> is this simply an update of current code

Yes, you are (of course) right. I can remove net7 and upate the pull request. Also remove the add support for net6 and mention that net461 and net5 will no longer be supported since they are out of support

**Comment by verrigo** [comment]
> 

So, there are two petapoco changes: One is removing the old petapoco package and using instead petapoco.compiled, since the current one is obsolete and the other change is in the PocoData class, where the change fixed issue https://github.com/DapperLib/Dapper/issues/1886

**Comment by NickCraver** [comment]
I think there's often a disconnect between "out of support" and "aren't being used" - those are not the same thing. What do we gain by dropping the support in the library? If there's no tangible benefit to dropping those working-as-is consumers, we err on the side of not doing that.

**Comment by verrigo** [comment]
I saw an Isuse created in 2019 where someone asked for net461 to be added again because of a situation where they could not upgrade to a newer version of visual studio. Reconsidering this PR, it looks like I didn't think it properly.

**Comment by NickCraver** [comment]
Going to close this out to tidy up - the removal isn't tenable for support on the breaking front.

**Pull request closed without merging**
