### PR TITLE
Can you Support Types on Descriptor API for preventing null objects in Grid Cells.

### PR DESCRIPTION
**Pull request by softwarekamal**
From Issue Here : https://github.com/StackExchange/Dapper/issues/1372

Problem that Descriptor API which works with `Query<dynamic>` and `DapperRow`, with null columns, it make Grid Cell Editors accept random keywords rather than only input from the Column `Type`, So can you please look at following fix:

**Modifications** 

**SqlMapper.DapperRow.Descriptor.cs**

```
                internal static PropertyDescriptorCollection GetProperties(DapperTable table, IDictionary<string,object> row = null)
                {
                    
                    string[] names = table?.FieldNames;
                    Type[] types = table?.FieldTypes;
                    if (names == null || names.Length == 0) return PropertyDescriptorCollection.Empty;
                    var arr = new PropertyDescriptor[names.Length];
                    for (int i = 0; i < arr.Length; i++)
                    {
                        var type = row != null && row.TryGetValue(names[i], out var value) && value != null
                            ? value.GetType() : types[i];
                        arr[i] = new RowBoundPropertyDescriptor(type, names[i], i);
                    }
                    return new PropertyDescriptorCollection(arr, true);
                }
```

**SqlMapper.cs**

```
  internal static Func<IDataReader, object> GetDapperRowDeserializer(IDataRecord reader, int startBound, int length, bool returnNullIfFirstMissing)
        {
            var fieldCount = reader.FieldCount;
            if (length == -1)
            {
                length = fieldCount - startBound;
            }

            if (fieldCount <= startBound)
            {
                throw MultiMapException(reader);
            }

            var effectiveFieldCount = Math.Min(fieldCount - startBound, length);

            DapperTable table = null;

            return
                r =>
                {
                    if (table == null)
                    {
                        string[] names = new string[effectiveFieldCount];
                        Type[] types = new Type[effectiveFieldCount];

                        for (int i = 0; i < effectiveFieldCount; i++)
                        {
                            names[i] = r.GetName(i + startBound);
                            types[i] = r.GetFieldType(i + startBound);
                        }

                        table = new DapperTable(names,types);
                    }

                    var values = new object[effectiveFieldCount];

                    if (returnNullIfFirstMissing)
                    {
                        values[0] = r.GetValue(startBound);
                        if (values[0] is DBNull)
                        {
                            return null;
                        }
                    }

                    if (startBound == 0)
                    {
                        for (int i = 0; i < values.Length; i++)
                        {
                            object val = r.GetValue(i);
                            values[i] = val is DBNull ? null : val;
                        }
                    }
                    else
                    {
                        var begin = returnNullIfFirstMissing ? 1 : 0;
                        for (var iter = begin; iter < effectiveFieldCount; ++iter)
                        {
                            object obj = r.GetValue(iter + startBound);
                            values[iter] = obj is DBNull ? null : obj;
                        }
                    }
                    return new DapperRow(table, values);
                };
        }
```

**DapperTable.cs**

```
     private sealed class DapperTable
        {
            private string[] fieldNames;
            private Type[] fieldTypes;
            private readonly Dictionary<string, int> fieldNameLookup;

            internal string[] FieldNames => fieldNames;
            internal Type[] FieldTypes => fieldTypes;

            public DapperTable(string[] fieldNames, Type[] fieldTypes)
            {
                this.fieldNames = fieldNames ?? throw new ArgumentNullException(nameof(fieldNames));
                this.fieldTypes = fieldTypes ?? throw new ArgumentNullException(nameof(fieldTypes));

                fieldNameLookup = new Dictionary<string, int>(fieldNames.Length, StringComparer.Ordinal);
                // if there are dups, we want the **first** key to be the "winner" - so iterate backwards
                for (int i = fieldNames.Length - 1; i >= 0; i--)
                {
                    string key = fieldNames[i];
                    if (key != null) fieldNameLookup[key] = i;
                }
            }
}
```

### CODE REVIEW

**Comment by mgravell** [comment]
Please check you have selected the right branch. This appears to be merging lots of my own code, and none of yours...?

**Comment by softwarekamal** [comment]
I can't PR in master branch. am new in Github maybe no privilages or something...

**Comment by softwarekamal** [comment]
I just upload modified areas in *.cs files. should i upload whole 3 files codes ?

**Comment by mgravell** [comment]
The usual workflow with git PRs goes something like the following:

1. you "fork" he project in GitHub; this creates a separate clone of the entire project in your name
2. you "clone" your fork onto your machine, which sets up the local file-system copy locally
3. you "branch" your clone, making a named area for your work
4. (make your changes, etc)
5. you "commit" your changes to your branch
6. you "push" the changes back to your fork/branch
7. you create a "pull request" from your fork/branch into the main repo

This sounds like a ton of work, but it is actually a lot simpler than it sounds.

I'd love to try and help you here - "teach someone to fish", so to speak. I did a quick search,and this looked moderately useful as a guide: https://thenewstack.io/getting-legit-with-git-and-github-your-first-pull-request/

**Comment by softwarekamal** [comment]
7.you create a "pull request" from your fork/branch into the main repo
you man after all of that, it will send to Main dapper repo. 

Can you please look at code or the problem i described, am really poor at github things -.-
I think this is issue for people who will use Query<dynamic> with Descriptor with NULL columns.
So please, am sorry for disturbing you if you can look at Issue or Copy the modified code. The descriptor you done will works great with Grids with NULL columns. 

I'll learn github soon. i really never use it before, so excuse me man :(

**Comment by rhubley** [comment]
I am also in need of the proper types from fields in a Dapper Row

I created #1409 to fix the git issue that was here.

**Comment by softwarekamal** [comment]
Hello, Its from long time post... I was think it fixed. The modification above is adding (Types variable in Descriptor API)
The section (Modifications) above explains changes. few lines changed.  
https://github.com/StackExchange/Dapper/pull/1373#issue-339572536

If you look up at modifications and compare it with above lines. You can see modifications.

https://github.com/rhubley  Try to PR it but maybe there's problem with github at time he post.
Am also have no experience with Github...

Am sorry because I had a problems in that time posted this Issue. that's why I keep this opened and not retrieve back to the Issue.

**Comment by NickCraver** [comment]
It's hard to tell what's happening here - the changeset is definitely not what's intended (seems to be git issues indeed). I recommend copy/pasting the actual intended changes into a new branch so that we can tell what's going on. It's hard to understand the issue since most of the diff is not related.

**Comment by NickCraver** [comment]
Ah looks like this is already done over in #1409 - closing out to cleanup!

**Pull request closed without merging**
